version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api 
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: space-flight-db